from django.conf.urls.defaults import patterns, include

urlpatterns = patterns( 'account.views', 
#	('^/?$', 'home', {}, 'website-home'),
	(r'^accounts/', include('nb.registration.urls')),
#	(r'^accounts/(?P<reg_no>\d+)/profile/$', 'UserProfileView', {}, 'website-profile-view'),
#	(r'^accounts/(?P<reg_no>\d+)/profile/personal-info/$', 'personal_info', {}, 'website-profile-personal-info'),
#	(r'^accounts/(?P<reg_no>\d+)/profile/edit/$', 'UserProfileEdit', {}, 'website-profile-edit'),
#	(r'^accounts/profile/editnew/$', 'UserProfileEditNew' , {} , 'website-profile-edit-new'),
#	(r'^accounts/(?P<reg_no>\d+)/profile/editnew/$', 'UserProfileEditNew' , {} , 'website-profile-edit-new'),        
#	('^people$', 'people', {}, 'website-people'),
#	('^people/([0-9]+)$', 'person', {}, 'website-person'),
#	('^page/([0-9]+)$', 'staticpage', {}, 'website-static'),
#	('^media$', 'allmedia', {}, 'website-media'),
#	('^pubs/(\d+)?/?$', 'publication', {}, 'website-publication'),
#	('^video/(\d+)?/?$', 'videos', {}, 'website-videos'),
#	('^audio/(\d+)?/?$', 'audios', {}, 'website-audios'),
#	('^image/(\d+)?/?$', 'images', {}, 'website-images'),
#	('^partner/(\d+)?/?$', 'partner', {}, 'website-partner'),
#	('^reference/(\d+)?/?$', 'reference', {}, 'website-reference'),
#	('^contact$', 'contact', {}, 'website-contact'),
#	('^services/?$', 'services', {}, 'website-services'),
#	('^services/corporate/(\d+)?/?$', 'corporateservices', {}, 'website-corporate-services'),
#	('^services/personal/(\d+)?/?$', 'personalservices', {}, 'website-personal-services'),
#	('^services/training/(\d+)?/?$', 'trainingservices', {}, 'website-training-services'),
#	('^css$', 'css', {}, 'website-css'),
#	('^js$', 'js', {}, 'website-js'),
)

